### ISSUE TITLE
Link math library in makefile for assignment 3_3

### ISSUE THREAD

**Issue by pvanagtmaal** [tu-os-course/TI2726C-Assignments-2016#1]
For assignment 3_3, we are supposed to calculate the standard deviation. One needs to take the square root of the sum of the squares of the deviations of each number from the average, and divide that by the total number of items in the list. However, since the makefile is not linking the math library, we are not able to use the sqrt function. Are we supposed to define one ourselves or have you forgotten to link it?

**Comment by ajrouvoet** [comment]
We forgot to link it in the makefile. If you want to, you can fork, fix and make a PR to fix it. I'll merge it today if you do. Otherwise I'll fix it tonight.

Thanks!

**Comment by ajrouvoet** [comment]
Oh, please let me know if you plan on making a PR

**Comment by pvanagtmaal** [comment]
I've just submitted a PR.
