### ISSUE TITLE
assignment 4

### ISSUE THREAD

**Issue by Danilodum** [tu-os-course/TI2726C-Assignments-2016#9]
review 900 by avanrijs on 2015-03-19 11:53:56 status Rejected
`On second thought, if you can remove the glitch that the leds briefly light up after each increment, you implemented it correctly!`

review 890 by avanrijs on 2015-03-19 11:41:39 status Rejected
`Thread 1 + 2 are not implemented correctly..`

`The objective for this assignment is to extend the 3.2 implementation. Thread one should be a binary counter that output its value to the leds. Thread 2 should count from 10 to 0 and back to 10. And Thread 3, lastly, is implemented correctly`

---

Can someone explain assignment 4? I thought it was about scheduling threads?

**Comment by ajrouvoet** [comment]
@electrotelligence ?
